# 异常类

> [!hint] 推荐自定义异常类直接继承自 Exception

| 成员变量           | 说明                |     |
| -------------- | ----------------- | --- |
| Data           | 额外信息              |     |
| HelpLink       | 链接到一个帮助文件         |     |
| InnerException | 若此异常为二次抛出，则为上一个异常 |     |
| Message        | 描述文本              |     |
| Source         | 异常程序或对象名          |     |
| StackTrace     | 堆栈信息              |     |

C# 内置异常类有：

| 类                      | 说明                                                                                                     |
| ---------------------- | ------------------------------------------------------------------------------------------------------ |
| SystemException        | .Net 运行库或几乎所有的应用抛出异常                                                                                   |
| ApplicationException   | 自定义应用异常类的基类。                                                                                           |
| StackOverflowException | 分配给栈的内存区域已满。<span style="background:#fff88f"><font color="#c00000">致命错误，有时甚至无法进入 finally</font></span> |
| EndOfStreamException   | 数据源的数据流读到文件末尾                                                                                          |
| OverflowException      | checked 环境下将 -40 的 int 转换为 uint                                                                        |

# 捕获

- 使用 `throw` 抛出异常
- 使用 `try - catch - finally` 结构捕获异常
- `catch` 接 `when` 对异常进一步过滤

```csharp
try
{
    // code
    throw new OverflowException();
}
catch(Exception e) when (e.InnerException == null) // 筛选
{
    // do someting
}
finally
{
    // clean up
}
```
